version: "3"
services:
  empproxy:
#    image: gresci/reallysimpleproxy
    build:
        context: .
        dockerfile: Dockerfile
    container_name: empproxy
    restart: always
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=empproxy"
      - "traefik.frontend.rule=Host:${PROXY_DOMAIN};PathPrefix:/emp"
      - "traefik.port=3001"
    env_file:
      - .env
    volumes:
      - ./app/index.js:/app/index.js

#networks:
#    default:
#      external:
#        name: 'nose_default'


